// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as JsxRuntime from "react/jsx-runtime";

function make(props) {
  var newrecord = Caml_obj.obj_dup(props);
  return JsxRuntime.jsx("button", (newrecord.className = "block cursor-pointer bg-rescript-500 py-3 px-4 my-16 mx-auto text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-rescript-600 hover:shadow-lg focus:bg-rescript-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-rescript-700 active:shadow-lg transition duration-150 ease-in-out", newrecord));
}

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
